import { CalendarEvent, Task, Project, TeamMemberRecord } from './types';

export const sampleTeamMembers: TeamMemberRecord[] = [
  { id: 'tm-roman', name: 'Roman', role: 'Founder & Creative Director', color: '#6366f1' },
  { id: 'tm-albina', name: 'Albina', role: 'Talent & Brand Partnerships', color: '#ec4899' },
  { id: 'tm-victoria', name: 'Victoria', role: 'Scriptwriter', color: '#10b981' },
  { id: 'tm-aliya', name: 'Aliya', role: 'Graphic Designer', color: '#f59e0b' },
];

export const sampleEvents: CalendarEvent[] = [
  {
    id: 'ep-s5e6',
    type: 'episode',
    title: 'S5E6 · Business myths',
    date: '2026-05-14',
    show: 'Privileged Gossip',
    episodeName: 'S5E6',
    theme: 'Business myths',
    linkedDealIds: [],
    stages: [
      { id: 'st1', name: 'Draft 1',   status: 'done',        startDate: '2026-05-14', endDate: '2026-05-19' },
      { id: 'st2', name: 'Comments',  status: 'done',        startDate: '2026-06-12', endDate: '2026-06-12' },
      { id: 'st3', name: 'Draft 2',   status: 'in_progress', startDate: '2026-06-13', endDate: '2026-06-17' },
      { id: 'st4', name: 'Comments',  status: 'not_started', startDate: '2026-06-17', endDate: '2026-06-17' },
      { id: 'st5', name: 'Draft 3',   status: 'not_started', startDate: '2026-06-18', endDate: '2026-06-21' },
      { id: 'st6', name: 'Comments',  status: 'not_started', startDate: '2026-06-22', endDate: '2026-06-22' },
      { id: 'st7', name: 'Final',     status: 'not_started', startDate: '2026-06-22', endDate: '2026-06-23' },
      { id: 'st8', name: 'Graphics',  status: 'in_progress', startDate: '2026-06-15', endDate: '2026-06-17' },
      { id: 'st9', name: 'Thumbnail', status: 'not_started', startDate: '2026-06-17', endDate: '2026-06-19' },
    ],
  },
  {
    id: 'ep-s6e1',
    type: 'episode',
    title: 'S6E1 · 29 Advice',
    date: '2026-06-15',
    show: 'Privileged Gossip',
    episodeName: 'S6E1',
    theme: '29 Advice',
    linkedDealIds: ['deal-bybit'],
    stages: [
      { id: 'st10', name: 'Draft 1',   status: 'not_started', startDate: '2026-06-15', endDate: '2026-06-18' },
      { id: 'st11', name: 'Comments',  status: 'not_started', startDate: '2026-06-19', endDate: '2026-06-19' },
      { id: 'st12', name: 'Draft 2',   status: 'not_started', startDate: '2026-06-22', endDate: '2026-06-25' },
      { id: 'st13', name: 'Comments',  status: 'not_started', startDate: '2026-06-26', endDate: '2026-06-26' },
      { id: 'st14', name: 'Draft 3',   status: 'not_started', startDate: '2026-06-29', endDate: '2026-06-30' },
      { id: 'st15', name: 'Comments',  status: 'not_started', startDate: '2026-07-01', endDate: '2026-07-01' },
      { id: 'st16', name: 'Final',     status: 'not_started', startDate: '2026-07-02', endDate: '2026-07-02' },
      { id: 'st17', name: 'Graphics',  status: 'not_started', startDate: '2026-06-22', endDate: '2026-06-24' },
      { id: 'st18', name: 'Thumbnail', status: 'not_started', startDate: '2026-06-29', endDate: '2026-07-03' },
    ],
  },
  {
    id: 'deal-qure',
    type: 'brand_deal',
    title: 'Qure Skincare — filming',
    date: '2026-06-20',
    brand: 'Qure Skincare',
    rate: 3500,
    currency: 'GBP',
    dealStage: 'filming',
    responsible: 'Albina',
  },
  {
    id: 'deal-bybit',
    type: 'brand_deal',
    title: 'Bybit — negotiation',
    date: '2026-06-25',
    brand: 'Bybit',
    rate: 5000,
    currency: 'GBP',
    dealStage: 'negotiation',
    responsible: 'Roman',
  },
  {
    id: 'deal-mvmt',
    type: 'brand_deal',
    title: 'MVMT — edit',
    date: '2026-07-01',
    brand: 'MVMT',
    rate: 1200,
    currency: 'GBP',
    dealStage: 'edit',
    responsible: 'Victoria',
  },
  {
    id: 'rem-1',
    type: 'reminder',
    title: 'Submit Q3 content plan to team',
    date: '2026-06-30',
    done: false,
    responsible: 'Roman',
  },
];

export const sampleTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Finalise Bybit contract terms',
    description: 'Review rate, usage rights, exclusivity window',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Roman',
    dueDate: '2026-06-20',
    tags: ['brand-deals'],
    recurring: null,
    createdAt: '2026-06-10T09:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Write S5E6 Draft 2 script',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Victoria',
    dueDate: '2026-06-05',
    projectId: 'proj-s6',
    tags: ['scripting'],
    recurring: null,
    createdAt: '2026-05-26T10:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Create Albina brand strategy deck',
    status: 'todo',
    priority: 'medium',
    assignee: 'Albina',
    dueDate: '2026-07-01',
    tags: ['strategy'],
    recurring: null,
    createdAt: '2026-06-10T09:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Weekly team check-in',
    status: 'todo',
    priority: 'low',
    assignee: 'Roman',
    tags: ['operations'],
    recurring: 'weekly',
    createdAt: '2026-06-01T09:00:00Z',
  },
  {
    id: 'task-5',
    title: 'S6E1 thumbnail brief to designer',
    status: 'todo',
    priority: 'medium',
    assignee: 'Roman',
    dueDate: '2026-07-05',
    projectId: 'proj-s6',
    tags: ['design'],
    recurring: null,
    createdAt: '2026-06-15T10:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Qure Skincare filming logistics',
    status: 'todo',
    priority: 'high',
    assignee: 'Albina',
    dueDate: '2026-06-18',
    tags: ['brand-deals', 'production'],
    recurring: null,
    createdAt: '2026-06-10T09:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Monthly analytics report',
    status: 'todo',
    priority: 'medium',
    assignee: 'Roman',
    tags: ['analytics'],
    recurring: 'monthly',
    createdAt: '2026-06-01T09:00:00Z',
  },
  {
    id: 'task-8',
    title: 'S5E6 graphics review',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Aliya',
    dueDate: '2026-06-22',
    projectId: 'proj-s6',
    tags: ['design'],
    recurring: null,
    createdAt: '2026-06-10T09:00:00Z',
  },
];

export const sampleProjects: Project[] = [
  {
    id: 'proj-s6',
    name: 'Season 6 Production',
    description: 'Privileged Gossip Season 6 — full production pipeline',
    color: '#6366f1',
    createdAt: '2026-06-01T00:00:00Z',
    phases: [
      {
        id: 'ph-1',
        name: 'Pre-Production',
        status: 'in_progress',
        startDate: '2026-06-01',
        endDate: '2026-06-30',
        taskIds: ['task-2'],
      },
      {
        id: 'ph-2',
        name: 'Production',
        status: 'not_started',
        startDate: '2026-07-01',
        endDate: '2026-07-31',
        taskIds: ['task-5'],
      },
      {
        id: 'ph-3',
        name: 'Post-Production',
        status: 'not_started',
        startDate: '2026-08-01',
        endDate: '2026-08-31',
        taskIds: ['task-8'],
      },
    ],
  },
  {
    id: 'proj-bd',
    name: 'Q3 Brand Deal Campaign',
    description: 'Bybit, Qure Skincare, MVMT — Q3 partnerships',
    color: '#f59e0b',
    createdAt: '2026-06-10T00:00:00Z',
    phases: [
      {
        id: 'ph-bd-1',
        name: 'Negotiation & Contracts',
        status: 'in_progress',
        startDate: '2026-06-10',
        endDate: '2026-06-25',
        taskIds: ['task-1'],
      },
      {
        id: 'ph-bd-2',
        name: 'Filming & Delivery',
        status: 'not_started',
        startDate: '2026-06-20',
        endDate: '2026-07-15',
        taskIds: ['task-6'],
      },
    ],
  },
];
